export const products = [
  {
    id: "1",
    categoria: "motos",
    subcategoria: "Racing",
    marca: "Yamaha",
    nombre: "Yamaha R1",
    descripcion:
      "Una moto deportiva de alta gama con tecnología de competición.",
    imagen: "https://example.com/yamaha_r1.jpg",
    precio: 18000,
    stock: true,
    kms: 1200,
    cc: "1000",
    tipo: "Racing",
  },
  {
    id: "2",
    categoria: "motos",
    subcategoria: "Adventure",
    marca: "BMW",
    nombre: "BMW GS 1200",
    descripcion:
      "La BMW GS 1200 es una moto diseñada para largas aventuras y rutas difíciles.",
    imagen: "https://example.com/bmw_gs1200.jpg",
    precio: 22000,
    stock: true,
    kms: 3000,
    cc: "1200",
    tipo: "Adventure",
  },
  {
    id: "3",
    categoria: "motos",
    subcategoria: "Naked",
    marca: "Ducati",
    nombre: "Ducati Monster 821",
    descripcion:
      "Ducati Monster 821 combina la potencia con el estilo clásico naked.",
    imagen: "https://example.com/ducati_monster821.jpg",
    precio: 15000,
    stock: true,
    kms: 800,
    cc: "821",
    tipo: "Naked",
  },
  {
    id: "4",
    categoria: "indumentaria",
    subcategoria: "Cascos",
    marca: "Shoei",
    nombre: "Shoei NXR",
    descripcion: "Casco de alta seguridad con diseño aerodinámico.",
    imagen: "https://example.com/shoei_nxr.jpg",
    precio: 450,
    stock: true,
    talla: "M",
    color: "Negro",
    material: "Fibra de carbono",
  },
  {
    id: "5",
    categoria: "indumentaria",
    subcategoria: "Chaquetas",
    marca: "Alpinestars",
    nombre: "Alpinestars GP Plus",
    descripcion:
      "Chaqueta de cuero de alta calidad para protección en carreras.",
    imagen: "https://example.com/alpinestars_gpplus.jpg",
    precio: 600,
    stock: true,
    talla: "L",
    color: "Rojo",
    material: "Cuero",
  },
  {
    id: "6",
    categoria: "indumentaria",
    subcategoria: "Guantes",
    marca: "Dainese",
    nombre: "Dainese Full Metal 6",
    descripcion: "Guantes de competición con refuerzos en carbono y titanio.",
    imagen: "https://example.com/dainese_fullmetal6.jpg",
    precio: 250,
    stock: true,
    talla: "L",
    color: "Negro",
    material: "Cuero",
  },
  {
    id: "7",
    categoria: "accesorios",
    subcategoria: "Escape",
    marca: "Akrapovic",
    nombre: "Escape Akrapovic Racing",
    descripcion: "Escape de alto rendimiento para motos deportivas.",
    imagen: "https://example.com/akrapovic_escape.jpg",
    precio: 1200,
    stock: true,
    compatible: ["Yamaha R1", "BMW S1000RR"],
    material: "Titanio",
  },
  {
    id: "8",
    categoria: "accesorios",
    subcategoria: "Baterías",
    marca: "Yuasa",
    nombre: "Yuasa YTZ10S",
    descripcion: "Batería de alto rendimiento para motos deportivas y touring.",
    imagen: "https://example.com/yuasa_ytz10s.jpg",
    precio: 120,
    stock: true,
    compatible: ["Honda CBR600", "Kawasaki Ninja 400"],
    capacidad: "12V",
  },
  {
    id: "9",
    categoria: "accesorios",
    subcategoria: "Neumáticos",
    marca: "Michelin",
    nombre: "Michelin Pilot Road 5",
    descripcion:
      "Neumáticos de gran durabilidad y agarre en superficies mojadas.",
    imagen: "https://example.com/michelin_pilotroad5.jpg",
    precio: 350,
    stock: true,
    compatible: ["Ducati Monster", "Triumph Street Triple"],
    medida: "120/70ZR17",
  },
  {
    id: "10",
    categoria: "indumentaria",
    subcategoria: "Botas",
    marca: "Sidi",
    nombre: "Sidi Crossfire 3",
    descripcion: "Botas de motocross con excelente protección y comodidad.",
    imagen: "https://example.com/sidi_crossfire3.jpg",
    precio: 500,
    stock: true,
    talla: "42",
    color: "Blanco",
    material: "Cuero sintético",
  },
];
